name = "worker-sites-template"
main = "src/index.js"
compatibility_date = "2022-05-06"

workers_dev = false
route = "elohimstudio.co/*"
zone_id = "e5eba835459a32da5afcdb8a159b3b0e"

site = { bucket = "./public" }